# Generated by Django 5.1.4 on 2025-01-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRANCHES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=23)),
                ('Description', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
