# Generated by Django 5.1.4 on 2025-01-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SALOON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=23)),
                ('Branch', models.CharField(max_length=22)),
                ('Description', models.CharField(max_length=100)),
                ('Emage', models.ImageField(default='null.jpeg', upload_to='emage')),
            ],
        ),
        migrations.RemoveField(
            model_name='branches',
            name='Description',
        ),
        migrations.AlterField(
            model_name='branches',
            name='Image',
            field=models.ImageField(default='null.jpeg', upload_to='image'),
        ),
    ]
