# Generated by Django 5.1.4 on 2025-01-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_saloon_remove_branches_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serv', models.CharField(max_length=50)),
                ('Salon', models.CharField(max_length=70)),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('IImage', models.ImageField(default='null.jpeg', upload_to='iimage')),
            ],
        ),
    ]
