# Generated by Django 5.1.4 on 2025-02-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_services'),
        ('userapp', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Time', models.CharField(default='9AM-1PM', max_length=20)),
                ('Note', models.CharField(max_length=250)),
                ('ServiceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.services')),
                ('userreg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.reg')),
            ],
        ),
    ]
