# Generated by Django 5.1.4 on 2025-02-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_services'),
        ('userapp', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='saloID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.saloon'),
        ),
    ]
