# Generated by Django 5.1.4 on 2025-02-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_book_saloid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approve',
            field=models.CharField(default='disapprove', max_length=10),
        ),
    ]
