# Generated by Django 5.1.4 on 2025-02-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_book_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='approve',
            new_name='status',
        ),
    ]
